// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// `dotenv/config` only reads a file named `.env`. Next.js keeps local secrets in
// `.env.local`, so load that too — without overriding vars already set in the
// real environment (so an inline `DATABASE_URL=... prisma ...` always wins).
loadEnv({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
